/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Profesores;

import Administrador.ActualizarProfesor;
import Administrador.AdministradorProfesores;
import static Administrador.AdministradorProfesores.apellido;
import static Administrador.AdministradorProfesores.codigo;
import static Administrador.AdministradorProfesores.contadorProfesores;
import static Administrador.AdministradorProfesores.contraseña;
import static Administrador.AdministradorProfesores.correo;
import static Administrador.AdministradorProfesores.fila;
import static Administrador.AdministradorProfesores.genero;
import static Administrador.AdministradorProfesores.nombre;
import Administrador.Profesor;
import ejemploproyecto1.Login;

/**
 *
 * @author USUARIO
 */
public class InicioProfesores extends javax.swing.JFrame {

    /**
     * Creates new form InicioProfesores
     */
    public InicioProfesores() {
        initComponents();
        //No se cambie el tamaño de la ventana
        this.setResizable(false);
        //Utilizado para visualizar en el centro la ventana
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CursoBtn = new javax.swing.JButton();
        AlumnosBtn = new javax.swing.JButton();
        ActualizarDatosBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Curso Asignado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        CursoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CursoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, 70));
        jPanel1.add(AlumnosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, 20));

        ActualizarDatosBtn.setText("Actualizar Datos");
        ActualizarDatosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarDatosBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarDatosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void ActualizarDatosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarDatosBtnActionPerformed
        // TODO add your handling code here:
        String codigo = AdministradorProfesores.codigo;
        String nombre = AdministradorProfesores.nombre;
        String apellido = AdministradorProfesores.apellido;
        String correo = AdministradorProfesores.correo;
        String contraseña = AdministradorProfesores.contraseña;
        String genero = AdministradorProfesores.genero;
        
        Profesor pr = new Profesor(codigo, nombre, apellido, correo, contraseña, genero);
        int fila = AdministradorProfesores.fila;
        AdministradorProfesores.profesores[fila] = pr;
        
        this.setVisible(false);
        ActualizarDatos ad = new ActualizarDatos();
        ad.setVisible(true);
    }//GEN-LAST:event_ActualizarDatosBtnActionPerformed

    private void CursoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursoBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdministracionCurso ap = new AdministracionCurso();
        ap.setVisible(true);
    }//GEN-LAST:event_CursoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioProfesores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarDatosBtn;
    private javax.swing.JButton AlumnosBtn;
    private javax.swing.JButton CursoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
